/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sonatype.patchtesting;

public class UnnecessaryParentheses
{
  public boolean unnecessaryParentheses() {
    String s = ("This is a string with UnnecessaryParentheses");
    /*
     * A comment for context
     */

    if ((s.length()) > 5) {
      System.out.println("Length is greater than 5!");
    }
    /*
     * More comment context
     */

    return (true);
  }
}
