/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sonatype.patchtesting;

import java.util.Scanner;

public class UnnecessaryParentheses
{
  public boolean unnecessaryParentheses() {
    String s =  new Scanner(System.in).nextLine();
    /*
     * A comment for context
     */

    new RuntimeException("ah");

    if ( s.length() > 5) {
      System.out.println("Length is greater than 5!");
    }
    /*
     * More comment context
     */

    return  true;
  }
}
